### ISSUE TITLE
Store payments

### ISSUE THREAD

**Issue by rolznz** [elnosh/gonuts#10]
Would it make sense for the wallet DB to also store (and support fetching) melts/payments, similar to how invoices are stored?

**Comment by elnosh** [comment]
yeah, I think it'd be nice to have something like that. I wanted to add something to build a transaction history of the wallet.

**Comment by rolznz** [comment]
@elnosh any update on this? we'd like to get the cashu LNClient merged for NWC

**Comment by elnosh** [comment]
hey @rolznz  sorry for delay. Will work on something for this
