### ISSUE TITLE
Random verification errors

### ISSUE THREAD

**Issue by tcheeric** [elnosh/gonuts#35]
Hello,

I am working on a Java implementation of the Cashu protocol, and I am facing an issue with the verification of proofs.
In my test, I mint 100 units (6 x 16 units + 1 x 4 units) but then, melting fails randomly. For example, I have tried to melt 32 units (2 x 16 units), the first proof gets verified but the second fails. I have spent several weeks troubleshooting and refactoring, but I was not able to find the problem.
I have tried yesterday to run my tests with your library, and was also surprised to see that it produces the same results as my library.

Here's my gist: https://gist.github.com/tcheeric/59ed616843bf4efa21032812a9da5969

I'd be grateful if you could have a look, and maybe you have an explanation for the failure?

Thanks.

**Comment by elnosh** [comment]
replied to you in the gist
