### ISSUE TITLE
Mint does not exist

### ISSUE THREAD

**Issue by kaichaosun** [elnosh/gonuts#4]
Running command `nutw send 1` or `nutw pay <invoice>` got error:
mint does not exist.

balance shows:
```
Balance by mint:

Mint 1: https://8333.space:3338 ---- balance: 1

Total balance: 1
```

**Comment by elnosh** [comment]
with the `send` or `pay` commands, it will ask you to select from which mint to send by passing the mint number. Since you only have one mint, are you specifying '1' when it asks for it?

Let me know if that works :)

**Comment by elnosh** [comment]
hey, thanks for reporting that. It should be fixed here https://github.com/elnosh/gonuts/commit/07ac8f3ce033ba922b511cdd845802ba5066c516. Let me know if it works with that :)

**Comment by elnosh** [comment]
yeah that is most likely because of fees. When asking the mint to pay an invoice for you, it will ask for a fee reserve in addition to the invoice amount. 
So if `invoice_amount` + `fee_reserve` > `your_balance` then it will not be able to pay the invoice.
