### ISSUE TITLE
wallet - method to check state of pending proofs

### ISSUE THREAD

**Issue by elnosh** [elnosh/gonuts#88]
after a send proofs are deleted. Instead, save as pending and add method to check state and reclaim them if still unspent

**Comment by rolznz** [comment]
@elnosh I think a few users of Alby Hub encountered this and I think their balance is stuck. Is there any way they can resolve it?

**Comment by elnosh** [comment]
@rolznz any specific error for how is the wallet stuck? what version are you using? 

a couple things that could help:
- if you are on v0.2.0, that version did not handle pending proofs if they got stuck in a payment. That could cause the wallet to try to use proofs that it thinks it can spend but it cannot. If on this version, I think it could help to restore the wallet using https://pkg.go.dev/github.com/elnosh/gonuts@v0.2.0/wallet#Restore 
- if on v0.3.0, there is a method to get the id of melt quotes that are pending https://pkg.go.dev/github.com/elnosh/gonuts@v0.3.0/wallet#Wallet.GetPendingMeltQuotes and then you could check the state of quote with https://pkg.go.dev/github.com/elnosh/gonuts@v0.3.0/wallet#Wallet.CheckMeltQuoteState that should update the state of pending proofs.

**Comment by rolznz** [comment]
@elnosh we are currently on 0.2.0, I have an open task to update to 0.3

What do you mean by **This will restart the wallet from scratch** - the user can still recover the funds they had in the wallet, right?

**Comment by elnosh** [comment]
> What do you mean by **This will restart the wallet from scratch** - the user can still recover the funds they had in the wallet, right?

Yes, that should recover the funds they had in the wallet. What I mean by that is that it will only recover funds (only the proofs it can spend), it won't restore previous wallet history like list of invoices.
