### ISSUE TITLE
Expose ListInvoices method

### ISSUE THREAD

**Issue by rolznz** [elnosh/gonuts#9]
Is there a way to retrieve all the invoices from the DB?

**Comment by elnosh** [comment]
currently no, only individually. Would you need to retrieve all of them or based on certain criteria? Like only redeemed invoices?

**Comment by rolznz** [comment]
Returning all the invoices as a first step would be ok, and I can filter them locally.

For NWC-specific requirements we would need filtering and paging options like in https://github.com/nostr-protocol/nips/blob/master/47.md#list_transactions
